import type { AstroIntegration } from 'astro';
import { i18nVitePlugin } from '../extraction/vite-plugin.js';
import type { I18nOptions } from './types.js';

const CLIENT_DIRECTIVES = ['load-x', 'idle-x', 'visible-x', 'media-x', 'only-x'] as const;

/**
 * Astro integration for i18n with automatic per-chunk translation loading.
 *
 * Registers:
 * - Client directives (`client:load-x`, `client:idle-x`, `client:visible-x`, `client:media-x`, `client:only-x`)
 * - Vite plugin for translation key extraction
 */
export default function i18nIntegration(_options: I18nOptions = {}): AstroIntegration {
  return {
    name: '@astroscope/i18n',
    hooks: {
      'astro:config:setup': ({ addClientDirective, updateConfig, logger }) => {
        for (const directive of CLIENT_DIRECTIVES) {
          const base = directive.replace('-x', '');
          addClientDirective({
            name: directive,
            entrypoint: `@astroscope/i18n/client-directives/${base}.js`,
          });
        }

        updateConfig({
          vite: {
            plugins: [i18nVitePlugin({ logger })],
          },
        });
      },
      'astro:config:done': ({ injectTypes }) => {
        // inject client directive types for LSP support
        const typeMap: Record<string, string> = {
          load: 'boolean',
          idle: 'boolean',
          visible: 'boolean | string',
          media: 'string',
          only: 'string',
        };

        const attributes = CLIENT_DIRECTIVES.map((d) => {
          const base = d.replace('-x', '');
          return `    'client:${d}'?: ${typeMap[base]};`;
        }).join('\n');

        injectTypes({
          filename: 'client-directives.d.ts',
          content: `// generated by @astroscope/i18n
declare namespace astroHTML.JSX {
  interface AstroBuiltinAttributes {
${attributes}
  }
}`,
        });
      },
    },
  };
}
